//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlClientNDP4_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class metal
    {
        public int metal_id { get; set; }
        public string metal_name { get; set; }
        public string symbol { get; set; }
    }
}
